gradle.properties
=> Update module version

random-ballerina/build.gradle
> Update ballerina command to bal command
=> Update ballerina command to bal command

random-ballerina/init.bal, random-ballerina/natives.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Change the name of the `java` langlib module to `jballerina.java`

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, random-ballerina/build.gradle
=> Enable publishing of code coverage

random-ballerina/build.gradle
=> Avoid running tests twice when publishing

random-ballerina/build.gradle
> Renames the extension of the package distribution file from balo to bala 
> Fixes ballerina-platform/ballerina-lang#28476
=> Replace balo with bala

random-ballerina/Package.md
=> Update Package.md with link to example

README.md, random-ballerina/Package.md
=> Rename module to package in Readme.md and Package.md

.github/workflows/publish-release.yml, build.gradle, gradle.properties, random-ballerina/build.gradle
=> Enable Publishing to Ballerina Central on Release

build.gradle, random-ballerina/build.gradle
=> Re-order build tasks to enable publishing to central

random-ballerina/build.gradle
=> Avoid publishing to central fro SNAPSHOT versions

random-ballerina/build.gradle
=> Fix ballerina push not working

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, random-ballerina/build.gradle
=> Remove publishing exec artifacts and archiving test json

random-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
=> Add extracted bala in the zip artifact

random-ballerina/tests/random.bal
=> Update with lang breaking changes

build.gradle, random-ballerina/build.gradle
=> Strip stdlib dependency version

.github/workflows/central-publish.yml, README.md, random-ballerina/build.gradle
=> Move Ballerina build, test and publish into a single task

random-ballerina/random_errors.bal, random-ballerina/tests/random.bal, random-native/src/main/java/org/ballerinalang/stdlib/random/nativeimpl/ExternMethods.java
$Subject
Related Issue: [#1288](https://github.com/ballerina-platform/ballerina-standard-library/issues/1288)
=> Improve the test coverage

random-ballerina/build.gradle
Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381
=> Set flag to enable Jacoco Coverage XML generation

README.md, random-ballerina/Module.md, random-ballerina/Package.md, random-ballerina/natives.bal
=> Improve API Docs and add Package.MD file

build-config/checkstyle/build.gradle, build.gradle, gradle.properties, random-ballerina/build.gradle
Standardize build script of Ballerina module
=> Apply Gradle Ballerina plugin for Ballerina module build script

gradle.properties, random-ballerina/build.gradle
=> Bump ballerina plugin version

random-ballerina/build.gradle
Remove overriding testCoverageParam and use the value from the gradle plugin.
=> Remove overriding testCoverageParam

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, random-ballerina/Package.md
$Subject
Related to ballerina-platform/ballerina-release#547 and ballerina-platform/ballerina-standard-library#1462
=> Update Package.md and workflow config

native/src/main/java/io/ballerina/stdlib/random/nativeimpl/Constant.java
$subject. This is to improve test coverage
=> Add private constructor in Constant class

.github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/trivy-scan.yml, ballerina/Dependencies.toml
https://github.com/ballerina-platform/ballerina-standard-library/issues/1958
=> Skip build directory from Trivy scan

.github/workflows/publish-release.yml, ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/build.gradle
https://github.com/ballerina-platform/ballerina-standard-library/issues/2033
=> Add files using git add before automated commit

docs/spec/spec.md
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2328
=> Add random module specification

ballerina/tests/random.bal
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2330
=> Improve code quality

ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
Related issue: ballerina-platform/ballerina-standard-library#2503
=> Minor version bump for GA release

ballerina/natives.bal
=> Improve API docs

docs/spec/spec.md
=> Fix formatting issue in spec

ballerina/natives.bal
=> Update createIntInRange function to exclude upper bound

ballerina/Dependencies.toml, gradle.properties
=> Update dependencies to the latest timestamp version

ballerina/build.gradle, gradle.properties
=> Update ballerina platform path in gradle task

ballerina/Dependencies.toml, ballerina/natives.bal, docs/spec/spec.md
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2876
=> Update `createDecimal` function to be cryptographically secure

gradle.properties
Reverts ballerina-platform/module-ballerina-random#395
=> Revert "Update latest time-stamped version of lang"

ballerina/build.gradle
=> Remove explicit ballerina platform path in gradle task

.github/workflows/build-with-bal-test-native.yml, ballerina/Ballerina.toml, ballerina/Dependencies.toml
https://github.com/ballerina-platform/ballerina-standard-library/issues/4142#issue-1604522669
=> Add GraalVM check for the pull requests

.github/workflows/build-with-bal-test-graalvm.yml, README.md, ballerina/Dependencies.toml, gradle.properties
$Subject 
Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/4548
=> Incoperate native build command change

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, README.md, ballerina/Ballerina.toml, ballerina/natives.bal, build-config/resources/Ballerina.toml, gradle.properties, gradle/wrapper/gradle-wrapper.properties, settings.gradle
=> Migrate to Java 17

README.md, gradle.properties, gradle/wrapper/gradle-wrapper.properties
=> Fix Oracle JDK download link

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, gradle.properties
=> Update Java version to 17.0.7 in workflows

.github/workflows/build-with-bal-test-graalvm.yml
> $Subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/4787
=> [2201.7.x]Add GraalVM Check for 2201.7.x branch

changelog.md
=> Update changelog history

README.md, changelog.md
Closes ballerina-platform/ballerina-standard-library#4893.
=> Remove duplicated codecov badge

.github/workflows/build-timestamped-master.yml, .github/workflows/build-with-bal-test-graalvm.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, README.md, ballerina/Ballerina.toml, build-config/resources/Ballerina.toml, changelog.md, gradle.properties
=> Migrate to Java 21

ballerina/Dependencies.toml, gradle.properties
=> Bumb versions for Java 21

gradle.properties
=> Update dependency versions for Update 11

ballerina/Ballerina.toml, ballerina/Dependencies.toml, gradle.properties
=> Upgrade dependencies for Update 12
